name             'chef-helper'
maintainer       'Wanelo, Inc'
maintainer_email 'dev@wanelo.com'
license          'All rights reserved'
description      'Keeps Chef up to date on your servers'
long_description 'Keeps Chef up to date on your servers'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
